#pragma once

#define TEST_PLAYER_INITIAL_NAME "Test Player"
#define TEST_PLAYER_INITIAL_CASH 3500
#define TEST_PLAYER_INITIAL_CURRENT_PAYMENT 0
#define TEST_PLAYER_INITIAL_POSITION 0
#define TEST_PLAYER_INITIAL_TARGET_POSITION 0
#define TEST_PLAYER_INITIAL_IN_MOVE false
#define TEST_PLAYER_INITIAL_TURNS_IN_JAIL 0
#define TEST_PLAYER_INITIAL_JAIL_CARDS 0